### ISSUE TITLE
where is kaldi_recognizer_wrap.cc

### ISSUE THREAD

**Issue by bihujrj** [alphacep/kaldi-android#4]
CMakeLIsts.txt need the file named kaldi_recognizer_wrap.cc ,but i cant find it.

add_library( kaldi_jni SHARED
             build/generated-src/cpp/kaldi_recognizer_wrap.cc
             ${API_SOURCES}
)

**Comment by nshmyrev** [comment]
It is created with swig here:

https://github.com/alphacep/kaldi-android/blob/65ebfb0dac600070affe8fa623979fd81a8120fa/build.gradle#L56

you are supposed to run `gradle build`, not cmake.

**Comment by bihujrj** [comment]
thank you ! i will try it again!

**Comment by bihujrj** [comment]
it works! thanks a lot!

**Comment by nshmyrev** [comment]
Ok, let us konw
